language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules
  yarn: true

notifications:
  email:
    on_success: never

script:
  - yarn lint
  - yarn test

deploy:
  - provider: script
    script: tools/pkg.sh
    skip_cleanup: true
    on:
      tags: true
